#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

## $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook starting..."

cat "${0}"

# $(echo "index.docker.io/user/respository" | cut -d '/' -f 3) = "repository"
APPLICATION=$(echo "${DOCKER_REPO}" | cut -d '/' -f 3)

echo "[---] DOCKERFILE_PATH:        ${DOCKERFILE_PATH}"
echo "[---] DOCKER_REPO:            ${DOCKER_REPO}"
echo "[---] IMAGE_NAME:             ${IMAGE_NAME}"
echo "[---] APPLICATION:            ${APPLICATION}"

# $(echo "index.docker.io/user/respository" | cut -d '/' -f 2-3) = "user/repository"
GITHUB_USERREPO=$(echo "${DOCKER_REPO}" | cut -d '/' -f 2-3)

# Set description from github
DESCRIPTION=$(curl -s https://api.github.com/repos/${GITHUB_USERREPO} \
    | grep '"description".*' \
    | head -n 1 \
    | cut -d '"' -f 4)

echo "[---] GITHUB_USERREPO:        ${GITHUB_USERREPO}"
echo "[---] DESCRIPTION:            ${DESCRIPTION}"

# Compiler setting
shopt -s extglob;
case "$IMAGE_NAME" in
    # ${DOCKER_REPO}:*?(\-)clang3.5?(\-*))
    #     CC=clang-3.5
    #     CXX=clang++-3.5
    #     ;;
    # ${DOCKER_REPO}:*?(\-)clang3.6?(\-*))
    #     CC=clang-3.6
    #     CXX=clang++-3.6
    #     ;;
    # ${DOCKER_REPO}:*?(\-)clang3.7?(\-*))
    #     CC=clang-3.7
    #     CXX=clang++-3.7
    #     ;;
    # ${DOCKER_REPO}:*?(\-)clang3.8?(\-*))
    #     CC=clang-3.8
    #     CXX=clang++-3.8
    #     ;;
    ${DOCKER_REPO}:*?(\-)clang3.9?(\-*))
        CC=clang-3.9
        CXX=clang++-3.9
        ;;
    ${DOCKER_REPO}:*?(\-)clang4.0?(\-*))
        CC=clang-4.0
        CXX=clang++-4.0
        ;;
    ${DOCKER_REPO}:*?(\-)clang5.0?(\-*))
        CC=clang-5.0
        CXX=clang++-5.0
        ;;
    ${DOCKER_REPO}:*?(\-)clang6.0?(\-*))
        CC=clang-6.0
        CXX=clang++-6.0
        ;;
    ${DOCKER_REPO}:*?(\-)clang7?(\-*))
        CC=clang-7
        CXX=clang++-7
        ;;
    ${DOCKER_REPO}:*?(\-)clang8?(\-*))
        CC=clang-8
        CXX=clang++-8
        ;;
    ${DOCKER_REPO}:*?(\-)clang9?(\-*))
        CC=clang-9
        CXX=clang++-9
        ;;
    # ${DOCKER_REPO}:*?(\-)clang10?(\-*))
    #     CC=clang-10
    #     CXX=clang++-10
    #     ;;
    # ${DOCKER_REPO}:*?(\-)gcc4.7?(\-*))
    #     CC=gcc-4.7
    #     CXX=g++-4.7
    #     FC=gfortran-4.7
    #     ;;
    ${DOCKER_REPO}:*?(\-)gcc4.8?(\-*))
        CC=gcc-4.8
        CXX=g++-4.8
        FC=gfortran-4.8
        ;;
    # ${DOCKER_REPO}:*?(\-)gcc4.9?(\-*))
    #     CC=gcc-4.9
    #     CXX=g++-4.9
    #     FC=gfortran-4.9
    #     ;;
    ${DOCKER_REPO}:*?(\-)gcc5?(\-*))
        CC=gcc-5
        CXX=g++-5
        FC=gfortran-5
        ;;
    ${DOCKER_REPO}:*?(\-)gcc6?(\-*))
        CC=gcc-6
        CXX=g++-6
        FC=gfortran-6
        ;;    
    ${DOCKER_REPO}:*?(\-)gcc7?(\-*))
        CC=gcc-7
        CXX=g++-7
        FC=gfortran-7
        ;;
    ${DOCKER_REPO}:*?(\-)gcc8?(\-*))
        CC=gcc-8
        CXX=g++-8
        FC=gfortran-8
        ;;
    # ${DOCKER_REPO}:*?(\-)gcc9?(\-*))
    #     CC=gcc-9
    #     CXX=g++-9
    #     FC=gfortran-9
    #     ;;
    # ${DOCKER_REPO}:*?(\-)gcc10?(\-*))
    #     CC=gcc-10
    #     CXX=g++-10
    #     FC=gfortran-10
    #     ;;
    *)
        echo "[***] Unsupported compiler"
        exit 1
        ;;
esac
shopt -u extglob;

echo "[---] CC:                     ${CC}"
echo "[---] CXX:                    ${CXX}"
echo "[---] FC:                     ${FC}"

# C++ standard
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)cxx11?(\-*))
        CMAKE_CXX_STANDARD=11
        ;;
    ${DOCKER_REPO}:*?(\-)cxx14?(\-*))
        CMAKE_CXX_STANDARD=14
        ;;
    ${DOCKER_REPO}:*?(\-)cxx17?(\-*))
        CMAKE_CXX_STANDARD=17
        ;;
    ${DOCKER_REPO}:*?(\-)cxx20?(\-*))
        CMAKE_CXX_STANDARD=20
        ;;
    ${DOCKER_REPO}:*?(\-)cxx98?(\-*))
        CMAKE_CXX_STANDARD=98
        ;;
    *)
        echo "[***] Unsupported C++ standard"
        exit 1
        ;;
esac
shopt -u extglob;

echo "[---] CMAKE_CXX_STANDARD:     ${CMAKE_CXX_STANDARD}"

# Build type
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)release?(\-*))
        CMAKE_BUILD_TYPE=Release
        ;;
    ${DOCKER_REPO}:*?(\-)debug?(\-*))
        CMAKE_BUILD_TYPE=Debug
        ;;
    ${DOCKER_REPO}:*?(\-)debinfo?(\-*))
        CMAKE_BUILD_TYPE=RelWithDebInfo
        ;;
    ${DOCKER_REPO}:*?(\-)minsize?(\-*))
        CMAKE_BUILD_TYPE=MinSizeRel
        ;;
    *)
        echo "[***] Unsupported build type"
        exit
        ;;
esac
shopt -u extglob;

echo "[---] CMAKE_BUILD_TYPE:       ${CMAKE_BUILD_TYPE}"

# Target architecture
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)auto?(\-*))
        TARGET_ARCHITECTURE="auto"
        ;;
    ${DOCKER_REPO}:*?(\-)none?(\-*))
        TARGET_ARCHITECTURE="none"
        ;;
    ${DOCKER_REPO}:*?(\-)generic?(\-*))
        TARGET_ARCHITECTURE="generic"
        ;;
    ${DOCKER_REPO}:*?(\-)core?(\-*))
        TARGET_ARCHITECTURE="core"
        ;;
    ${DOCKER_REPO}:*?(\-)merom?(\-*))
        TARGET_ARCHITECTURE="merom"
        ;;
    ${DOCKER_REPO}:*?(\-)penryn?(\-*))
        TARGET_ARCHITECTURE="penryn"
        ;;
    ${DOCKER_REPO}:*?(\-)nehalem?(\-*))
        TARGET_ARCHITECTURE="nehalem"
        ;;
    ${DOCKER_REPO}:*?(\-)westmere?(\-*))
        TARGET_ARCHITECTURE="westmere"
        ;;
    ${DOCKER_REPO}:*?(\-)sandybridge?(\-*))
        TARGET_ARCHITECTURE="sandybridge"
        ;;
    ${DOCKER_REPO}:*?(\-)ivybridge?(\-*))
        TARGET_ARCHITECTURE="ivybridge"
        ;;
    ${DOCKER_REPO}:*?(\-)haswell?(\-*))
        TARGET_ARCHITECTURE="haswell"
        ;;
    ${DOCKER_REPO}:*?(\-)broadwell?(\-*))
        TARGET_ARCHITECTURE="broadwell"
        ;;
    ${DOCKER_REPO}:*?(\-)skylake?(\-*))
        TARGET_ARCHITECTURE="skylake"
        ;;
    ${DOCKER_REPO}:*?(\-)skylake-xeon?(\-*))
        TARGET_ARCHITECTURE="skylake-xeon"
        ;;
    ${DOCKER_REPO}:*?(\-)kabylake?(\-*))
        TARGET_ARCHITECTURE="kabylake"
        ;;
    ${DOCKER_REPO}:*?(\-)cannonlake?(\-*))
        TARGET_ARCHITECTURE="cannonlake"
        ;;
    ${DOCKER_REPO}:*?(\-)cascadelake?(\-*))
        TARGET_ARCHITECTURE="cascadelake"
        ;;
    ${DOCKER_REPO}:*?(\-)cooperlake?(\-*))
        TARGET_ARCHITECTURE="cooperlake"
        ;;
    ${DOCKER_REPO}:*?(\-)icelake?(\-*))
        TARGET_ARCHITECTURE="icelake"
        ;;
    ${DOCKER_REPO}:*?(\-)icelake-xeon?(\-*))
        TARGET_ARCHITECTURE="icelake-xeon"
        ;;
    ${DOCKER_REPO}:*?(\-)tigerlake?(\-*))
        TARGET_ARCHITECTURE="tigerlake"
        ;;
    ${DOCKER_REPO}:*?(\-)alderlake?(\-*))
        TARGET_ARCHITECTURE="alderlake"
        ;;
    ${DOCKER_REPO}:*?(\-)sapphirerapids?(\-*))
        TARGET_ARCHITECTURE="sapphirerapids"
        ;;
    ${DOCKER_REPO}:*?(\-)bonnell?(\-*))
        TARGET_ARCHITECTURE="bonnell"
        ;;
    ${DOCKER_REPO}:*?(\-)silvermont?(\-*))
        TARGET_ARCHITECTURE="silvermont"
        ;;
    ${DOCKER_REPO}:*?(\-)goldmont?(\-*))
        TARGET_ARCHITECTURE="goldmont"
        ;;
    ${DOCKER_REPO}:*?(\-)goldmont-plus?(\-*))
        TARGET_ARCHITECTURE="goldmont-plus"
        ;;
    ${DOCKER_REPO}:*?(\-)tremont?(\-*))
        TARGET_ARCHITECTURE="tremont"
        ;;
    ${DOCKER_REPO}:*?(\-)knl?(\-*))
        TARGET_ARCHITECTURE="knl"
        ;;
    ${DOCKER_REPO}:*?(\-)knm?(\-*))
        TARGET_ARCHITECTURE="knm"
        ;;
    ${DOCKER_REPO}:*?(\-)atom?(\-*))
        TARGET_ARCHITECTURE="atom"
        ;;
    ${DOCKER_REPO}:*?(\-)k8?(\-*))
        TARGET_ARCHITECTURE="k8"
        ;;
    ${DOCKER_REPO}:*?(\-)k8-sse3?(\-*))
        TARGET_ARCHITECTURE="k8-sse3"
        ;;
    ${DOCKER_REPO}:*?(\-)barcelona?(\-*))
        TARGET_ARCHITECTURE="barcelona"
        ;;
    ${DOCKER_REPO}:*?(\-)istanbul?(\-*))
        TARGET_ARCHITECTURE="istanbul"
        ;;
    ${DOCKER_REPO}:*?(\-)magny-cours?(\-*))
        TARGET_ARCHITECTURE="magny-cours"
        ;;
    ${DOCKER_REPO}:*?(\-)bulldozer?(\-*))
        TARGET_ARCHITECTURE="bulldozer"
        ;;
    ${DOCKER_REPO}:*?(\-)interlagos?(\-*))
        TARGET_ARCHITECTURE="interlagos"
        ;;
    ${DOCKER_REPO}:*?(\-)piledriver?(\-*))
        TARGET_ARCHITECTURE="piledriver"
        ;;
    ${DOCKER_REPO}:*?(\-)steamroller?(\-*))
        TARGET_ARCHITECTURE="steamroller"
        ;;
    ${DOCKER_REPO}:*?(\-)excavator?(\-*))
        TARGET_ARCHITECTURE="excavator"
        ;;
    ${DOCKER_REPO}:*?(\-)amd14h?(\-*))
        TARGET_ARCHITECTURE="amd14h"
        ;;
    ${DOCKER_REPO}:*?(\-)amd16h?(\-*))
        TARGET_ARCHITECTURE="amd16h"
        ;;
    ${DOCKER_REPO}:*?(\-)zen3?(\-*))
        TARGET_ARCHITECTURE="zen3"
        ;;
    ${DOCKER_REPO}:*?(\-)zen2?(\-*))
        TARGET_ARCHITECTURE="zen2"
        ;;
    ${DOCKER_REPO}:*?(\-)zen?(\-*))
        TARGET_ARCHITECTURE="zen"
        ;;
    *)
        TARGET_ARCHITECTURE="generic"
        ;;
esac
shopt -u extglob;

echo "[---] TARGET_ARCHITECTURE:    ${TARGET_ARCHITECTURE}"

# Build with Trilinos support
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)trilinos?(\-*))
        GISMO_WITH_TRILINOS=ON
        GISMO_WITH_MPI=ON
        ;;
    *)
        GISMO_WITH_TRILINOS=OFF
        ;;
esac
shopt -u extglob;

# Build with OpenMP support
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)clang?(\-*)|${DOCKER_REPO}:*?(\-)noomp?(\-*))
        GISMO_WITH_OPENMP=OFF
        ;;
    ${DOCKER_REPO}:*?(\-)omp?(\-*))
        GISMO_WITH_OPENMP=ON
        ;;
    *)
        GISMO_WITH_OPENMP=ON
        ;;
esac
shopt -u extglob;

# Build with MPI support
shopt -s extglob;
case "$IMAGE_NAME" in
    ${DOCKER_REPO}:*?(\-)nompi?(\-*))
        GISMO_WITH_MPI=OFF
        ;;
    ${DOCKER_REPO}:*?(\-)mpi?(\-*))
        GISMO_WITH_MPI=ON
        ;;
    *)
        if [ -z {GISMO_WITH_MPI+x} ]; then
            GISMO_WITH_MPI=OFF
        fi
        ;;
esac
shopt -u extglob;

if [[ "${GISMO_WITH_TRILINOS}" == "ON" && "${GISMO_WITH_MPI}" != "ON" ]]; then
    echo "[***] Compiling G+Smo with Trilinos support enabled requires GISMO_WITH_MPI=ON"
    exit 1
fi

echo "[---] GISMO_WITH_OPENMP:      ${GISMO_WITH_OPENMP}"
echo "[---] GISMO_WITH_MPI:         ${GISMO_WITH_MPI}"
echo "[---] GISMO_WITH_TRILINOS:    ${GISMO_WITH_TRILINOS}"
exit 1
## Build the prime image at the end.
if [ -z "$FC" ]
then
    docker build \
           --file "${DOCKERFILE_PATH}" \
           --build-arg APPLICATION=${APPLICATION} \
           --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
           --build-arg COMMIT=$(git rev-parse --short HEAD) \
           --build-arg DESCRIPTION="${DESCRIPTION}" \
           --build-arg VERSION=$(git describe --tags --always) \
           --build-arg CC=${CC} \
           --build-arg CXX=${CXX} \
           --build-arg FC=${FC} \
           --build-arg CMAKE_BUILD_TYPE=${GISMO_BUILD_TYPE} \
           --build-arg CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} \
           --build-arg GISMO_WITH_MPI=${GISMO_WITH_MPI} \
           --build-arg GISMO_WITH_OPENMP=${GISMO_WITH_OPENMP} \
           --build-arg GISMO_WITH_TRILINOS=${GISMO_WITH_TRILINOS} \
           --build-arg TARGET_ARCHITECTURE=${TARGET_ARCHITECTURE} \
           -t ${IMAGE_NAME} \
           .
else
    docker build \
           --file "${DOCKERFILE_PATH}" \
           --build-arg APPLICATION=${APPLICATION} \
           --build-arg BUILD_RFC3339=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
           --build-arg COMMIT=$(git rev-parse --short HEAD) \
           --build-arg DESCRIPTION="${DESCRIPTION}" \
           --build-arg VERSION=$(git describe --tags --always) \
           --build-arg CC=${CC} \
           --build-arg CXX=${CXX} \
           --build-arg CMAKE_BUILD_TYPE=${GISMO_BUILD_TYPE} \
           --build-arg CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD} \
          --build-arg GISMO_WITH_MPI=${GISMO_WITH_MPI} \
           --build-arg GISMO_WITH_OPENMP=${GISMO_WITH_OPENMP} \
           --build-arg TARGET_ARCHITECTURE=${TARGET_ARCHITECTURE} \
           -t ${IMAGE_NAME} \
           .
fi

## Push image
docker push ${IMAGE_NAME}

echo "[***] ...build hook complete."
